
      PROGRAM SMACPATH
C     Version 11-12-97
C     SIMULATION MODEL OF AUTOMOBILE COLLISIONS -SMAC
C     PROGRAM VERSION 10-31-78
C
C     THE FOLLOWING MODIFICATIONS HAVE BEEN MADE TO THE ORIGINAL SOURCE
C     RECEIVED FROM CALSPAN
C
C     MOVE COMMON BLOCK/CONST/ TO MAIN PROGRAM
C     USE FILE UNITS 15, 16 FOR INPUT, OUTPUT
C
      COMMON/CONST/ G,RAD,PI,TWOPI,PIO2,PI32,ND2,ND4,ND8,NIN,NOUT
      COMMON/DELAY/ DY1L(11),DY2L(11),YAW1L(11),YAW2L(11)
     1              ,DYAW1L(11),DYAW2L(11),TDGT,DTDGT,IDLY,JDLY
      COMMON/YCOMP/ FREQA,FREQB,TL1,TL2,YL1,YL2,PYL1,PYL2
      COMMON/STRRATE/ DTACT,ILMT(4),RLMT,TLST(4),PLAST(4)
      COMMON/OTHERFILES/ NOUT1, NOUT2
C
C
      G     = 386.4
      RAD   = .0174532925
      PI    = 3.1415926536
      TWOPI = 2.0 * PI
      PIO2  = 0.5 * PI
      PI32  = 1.5 * PI
      ND2   = 2
      ND4   = 4
      ND8   = 8
      NIN   = 15
      NOUT  = 16
C
C     ENTER DELAY PARAMETERS
C
      IDLY = 1
      JDLY = 2
      TDGT = 0.1
      DTDGT = 0.01
      DO 10 I =1,11
         DY1L(I) = 0.0
         DY2L(I) = 0.0
         YAW1L(I) = 0.0
         YAW2L(I) = 0.0
         DYAW1L(I) = 0.0
         DYAW2L(I) = 0.0
   10 CONTINUE
C
C     ENTER LIMITS OF STEERING RATE
C
      DTACT = 0.1
      ILMT(1) = 0
      ILMT(2) = 0
      ILMT(3) = 0
      ILMT(4) = 0
      RLMT = 30
C      WRITE(6,*) 'ENTER RATE LIMIT OF STEERING ACTUATOR (DEG/SEC):'
C      READ(5,*) RLMT
      TLST(1) = 0.0
      TLST(2) = 0.0
      TLST(3) = 0.0
      TLST(4) = 0.0
      PLAST(1) = 0.0
      PLAST(2) = 0.0
      PLAST(3) = 0.0
      PLAST(4) = 0.0
C
C     ENTER POSITION COMPENSATOR
C
      FREQA = 0.02*TWOPI
      FREQB = 0.1*TWOPI
      TL1 = 0.0
      TL2 = 0.0
      YL1 = 0.0
      YL2 = 0.0
      PYL1 = 0.0
      PYL2 = 0.0
C
C       OPEN ADDITIONAL FILES FOR OPTIONS
      NOUT1 = 17
      NOUT2 = 18
C
C     OPEN FILES FOR INPUT AND OUTPUT
C
      OPEN (UNIT=NIN, FILE='INPUT.DAT')
      OPEN (UNIT=NOUT, FILE='OUTPUT.DAT', STATUS='UNKNOWN')
      OPEN (UNIT=NOUT1, FILE='VEH1.DAT', STATUS='UNKNOWN')
      OPEN (UNIT=NOUT2, FILE='VEH2.DAT', STATUS='UNKNOWN')
C
C     CALL SMAC
C
      CALL SMAC
C
C     CLOSE FILES
C
      CLOSE(NIN)
      CLOSE(NOUT)
      CLOSE(NOUT1)
      CLOSE(NOUT2)

      STOP
      END
